### ISSUE TITLE
--url file:///foo/bar/ with policy of on_demand or streamed raises unhandled RuntimeError

### ISSUE THREAD

**Issue by jakegatsby** [pulp/pulp_file#997]
**Version**

Using the all-in-one pulp container with pulpcore 3.28.1 and pulp-file 1.14.3

**Describe the bug**

With a remote with --url file:///foo/bar/ using either on_demand or streamed policy, when attempting to retrieve a file via wget, a 500 Internal Server Error is returned, and the logs show an unhandled RunTimeError

**To Reproduce**

```
pulp file remote create --name foobar --url file:///foo/bar/ --policy on_demand
...
wget http://myserver/pulp/content/foobar/somefile
...
HTTP request sent, awaiting response... 500 Internal Server Error
2023-07-08 01:19:34 ERROR 500: Internal Server Error.
```

**Expected behavior**

The file is successfully downloaded

**Additional context**

I mentioned this issue in IRC and it was confirmed as reproducible

**Comment by ggainey** [comment]
Reproduced using pulp_rpm. The problem is definitely in pulpcore. I'm moving this issue to the correct component.

RPM Reproducer:
```
# get a small RPM repo to a local-dir on the Pulp instance
$ cd /tmp
$ wget --recursive --no-parent https://fixtures.pulpproject.org/rpm-signed/
# Sync and distribute it
$ pulp rpm remote create --name foo --url file:///tmp/fixtures.pulpproject.org/rpm-signed/ --policy on_demand
$ pulp rpm repository create --name foo --remote foo --autopublish
$ pulp rpm repository sync --name foo
$ pulp rpm distribution create --name foo --repository foo --base-path foo
$ wget http://localhost:5001/pulp/content/foo/Packages/b/bear-4.1-1.noarch.rpm
--2023-07-12 13:52:28--  http://localhost:5001/pulp/content/foo/Packages/b/bear-4.1-1.noarch.rpm
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:5001... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:5001... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2023-07-12 13:52:28 ERROR 500: Internal Server Error.
$ 
```

Same traceback in logs:
```
[pulp]  | 127.0.0.1 [12/Jul/2023:13:48:44 +0000] "GET /pulp/content/foo/Packages/b/bear-4.1-1.noarch.rpm HTTP/1.0" 500 315 "http://localhost:5001/pulp/content/foo/Packages/b/" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
[2023-07-12 13:52:28 +0000] [1366] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib64/python3.8/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib64/python3.8/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib64/python3.8/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/src/pulpcore/pulpcore/content/authentication.py", line 48, in authenticate
    return await handler(request)
  File "/src/pulpcore/pulpcore/content/handler.py", line 248, in stream_content
    return await self._match_and_stream(path, request)
  File "/src/pulpcore/pulpcore/content/handler.py", line 611, in _match_and_stream
    return await self._stream_content_artifact(
  File "/src/pulpcore/pulpcore/content/handler.py", line 764, in _stream_content_artifact
    response = await self._stream_remote_artifact(request, response, remote_artifact)
  File "/src/pulpcore/pulpcore/content/handler.py", line 1042, in _stream_remote_artifact
    download_result = await downloader.run()
  File "/src/pulpcore/pulpcore/download/base.py", line 257, in run
    return await self._run(extra_data=extra_data)
  File "/src/pulpcore/pulpcore/download/file.py", line 58, in _run
    await self.handle_data(chunk)
  File "/src/pulpcore/pulpcore/content/handler.py", line 1027, in handle_data
    await response.write(data)
  File "/usr/local/lib64/python3.8/site-packages/aiohttp/web_response.py", line 512, in write
    raise RuntimeError("Cannot call write() before prepare()")
RuntimeError: Cannot call write() before prepare()
```
